override nvidia * extra/nvidia-open
override nvidia-drm * extra/nvidia-open
override nvidia-modeset * extra/nvidia-open
override nvidia-uvm * extra/nvidia-open
override nvidia-peermem * extra/nvidia-open
